/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import Classes.Dokter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import Classes.Pasien;
/**
 *
 * @author LENOVO C740
 */
public class DokterLogin extends javax.swing.JFrame {
    // Fields
    static private Dokter pengguna;
    /**
     * Creates new form DokterLogin
     */
    public DokterLogin() {
        initComponents();
         // mengambil ukuran layar
         Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

         // membuat titik x dan y
         int x = layar.width / 2  - this.getSize().width / 2;
         int y = layar.height / 2 - this.getSize().height / 2;
 
         this.setLocation(x, y);
    }

    /**
     * Sebuah Method untuk mengecek id dari database
     * @param id
     * @return dataWujud
     * @throws IOException
     */
   private static boolean checkID(String id) throws IOException
   {
       boolean dataWujud = true;
       // Membuak file database
       FileReader fileReader = new FileReader("DatabaseDokter.txt");
       BufferedReader bufferedReader = new BufferedReader(fileReader);
       // Mencari id di file database tersebut
       String data = bufferedReader.readLine();
       StringTokenizer stringTokenizer = new StringTokenizer(data,",");
       // Membaca keseluruhan file
       while(data != null){
           stringTokenizer = new StringTokenizer(data,",");
           // Kondisi jika ditemukan id pekerja
           if(id.equals(stringTokenizer.nextToken())){
               dataWujud = true;
               break;
           }else{
               dataWujud = false;
           }
           // Membaca baris setelahnya
           data = bufferedReader.readLine();
       }
       // wajib tutup!!!
       bufferedReader.close();
       return dataWujud;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginTextDokter = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegistrasi = new javax.swing.JButton();
        jBSignUp = new javax.swing.JButton();
        tfPIN = new javax.swing.JTextField();
        tfID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        LoginTextDokter.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        LoginTextDokter.setText("LOGIN");
        jPanel1.add(LoginTextDokter);
        LoginTextDokter.setBounds(330, 90, 160, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("PIN\n");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 310, 50, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 210, 50, 29);

        jButtonRegistrasi.setBackground(new java.awt.Color(204, 204, 204));
        jButtonRegistrasi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegistrasi.setText("SIGN IN");
        jButtonRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrasiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrasi);
        jButtonRegistrasi.setBounds(450, 420, 100, 25);

        jBSignUp.setBackground(new java.awt.Color(204, 204, 204));
        jBSignUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBSignUp.setText("SIGN UP");
        jBSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(jBSignUp);
        jBSignUp.setBounds(270, 420, 100, 25);
        jPanel1.add(tfPIN);
        tfPIN.setBounds(270, 340, 310, 40);

        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });
        jPanel1.add(tfID);
        tfID.setBounds(270, 240, 310, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Blank.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -20, 930, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSignUpActionPerformed
       DokterSignUp objekDokterSignUp = new DokterSignUp();
       objekDokterSignUp.setVisible(true);
       dispose();
    }//GEN-LAST:event_jBSignUpActionPerformed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
       
    }//GEN-LAST:event_tfIDActionPerformed

    private void jButtonRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrasiActionPerformed
        String id;
        int pin;
        id = tfID.getText();
        pin = Integer.parseInt(tfPIN.getText());
        // membuat objek pasien
        Pasien objekPasien  = new Pasien();
        jadwalKondisiPertama jadwalKondisiPertama = new jadwalKondisiPertama();
        jadwalKondisiKedua jadwalKondisiKedua = new jadwalKondisiKedua();
        jadwalKondisiKetiga jadwalKondisiKetiga = new jadwalKondisiKetiga();
        jadwalKondisiKeempat jadwalKondisiKeempat = new jadwalKondisiKeempat();
        try {
            if(checkID(id)){
                pengguna = new Dokter(id);
                if(pin == pengguna.getPin()){ 
                    if(objekPasien.getJamKerjaMinimal() == 3){
                    jadwalKondisiPertama.setVisible(true);
                    dispose();
                }else if(objekPasien.getJamKerjaMinimal() == 5){
                    jadwalKondisiKedua.setVisible(true);
                    dispose();
                }else if(objekPasien.getJamKerjaMinimal() == 8){
                    jadwalKondisiKetiga.setVisible(true);
                    dispose();
                }else{
                    jadwalKondisiKeempat.setVisible(true);
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID DAN PIN ANDA TIDAK DITEMUKAN SILAHKAN MENDAFTAR DI BAGIAN SIGN UP ");
            }
               
            }else{
                JOptionPane.showMessageDialog(this, "ID DAN PIN ANDA TIDAK DITEMUKAN SILAHKAN MENDAFTAR DI BAGIAN SIGN UP ");
            }
        } catch (IOException e) {
            
        }
        
    }//GEN-LAST:event_jButtonRegistrasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DokterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DokterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DokterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DokterLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DokterLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoginTextDokter;
    private javax.swing.JButton jBSignUp;
    private javax.swing.JButton jButtonRegistrasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfPIN;
    // End of variables declaration//GEN-END:variables
}
