/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import Classes.Pegawai;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
/**
 * Sebuah class untuk melakukan proses lagin pada pegawai
 * @author Alphancoders
 * @version 2021.11.28
 */
public class PegawaiLogin extends javax.swing.JFrame {
    // Fields
    static private Pegawai pengguna;
    /**
     * Creates new form PegawaiLogin
     */
    public PegawaiLogin() {
        initComponents();
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    private static boolean checkID(String id) throws IOException
   {
       boolean dataWujud = true;
       // Membuka file database
       FileReader fileReader = new FileReader("DatabasePegawai.txt");
       BufferedReader bufferedReader = new BufferedReader(fileReader);
       // Mencari id di file database tersebut
       String data = bufferedReader.readLine();
       StringTokenizer stringTokenizer = new StringTokenizer(data,",");
       // Membaca keseluruhan file
       while(data != null){
           stringTokenizer = new StringTokenizer(data,",");
           // Kondisi jika ditemukan id pekerja
           if(id.equals(stringTokenizer.nextToken())){
               dataWujud = true;
               break;
           }else{
               dataWujud = false;
           }
           // Membaca baris setelahnya
           data = bufferedReader.readLine();
       }
       // wajib tutup!!!
       bufferedReader.close();
       return dataWujud;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LoginTitle = new javax.swing.JLabel();
        IDtitle = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        PINtitle = new javax.swing.JLabel();
        PIN = new javax.swing.JTextField();
        BSignIn = new javax.swing.JButton();
        BSignUp = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        LoginTitle.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        LoginTitle.setText("LOGIN");
        jPanel1.add(LoginTitle);
        LoginTitle.setBounds(360, 90, 160, 90);

        IDtitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        IDtitle.setText("ID");
        jPanel1.add(IDtitle);
        IDtitle.setBounds(270, 190, 50, 29);
        jPanel1.add(ID);
        ID.setBounds(270, 220, 340, 40);

        PINtitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        PINtitle.setText("PIN");
        jPanel1.add(PINtitle);
        PINtitle.setBounds(270, 290, 50, 30);
        jPanel1.add(PIN);
        PIN.setBounds(270, 320, 340, 40);

        BSignIn.setBackground(new java.awt.Color(204, 204, 204));
        BSignIn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BSignIn.setText("SIGN IN");
        BSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSignInActionPerformed(evt);
            }
        });
        jPanel1.add(BSignIn);
        BSignIn.setBounds(490, 390, 120, 30);

        BSignUp.setBackground(new java.awt.Color(204, 204, 204));
        BSignUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BSignUp.setText("SIGN UP");
        BSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(BSignUp);
        BSignUp.setBounds(270, 390, 110, 30);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Blank.png"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(0, 0, 920, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSignUpActionPerformed
        PegawaiSignUp PegawaiSignUp = new PegawaiSignUp();
        PegawaiSignUp.setVisible(true);
        dispose();
    }//GEN-LAST:event_BSignUpActionPerformed

    private void BSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSignInActionPerformed
        String id;
        int pin;
        id = ID.getText();
        pin = Integer.parseInt(PIN.getText());
        // Membuat Objek
        jadwalTetapPegawai jadwalTetapPegawai= new jadwalTetapPegawai();
        try {
            if(checkID(id)){
                pengguna = new Pegawai(id);
                if(pin == pengguna.getPin()){
                    jadwalTetapPegawai.setVisible(true);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "ID DAN PIN ANDA TIDAK DITEMUKAN SILAHKAN MENDAFTAR DI SIGN UP");
                }
            }else{
                JOptionPane.showMessageDialog(this, "ID DAN PIN ANDA TIDAK DITEMUKAN SILAHKAN MENDAFTAR DI SIGN UP");
            }
        } catch (Exception e) {
           
        }

        
    }//GEN-LAST:event_BSignInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PegawaiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PegawaiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PegawaiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PegawaiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PegawaiLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton BSignIn;
    private javax.swing.JButton BSignUp;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel IDtitle;
    private javax.swing.JLabel LoginTitle;
    private javax.swing.JTextField PIN;
    private javax.swing.JLabel PINtitle;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
