/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author LENOVO C740
 */
public class SetRole extends javax.swing.JFrame {

    /**
     * Creates new form SetRole
     */
    public SetRole() {
        initComponents();
        // mengambil ukuran layar
        Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();

        // membuat titik x dan y
        int x = layar.width / 2  - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonDokter = new javax.swing.JButton();
        ButtonPerawat = new javax.swing.JButton();
        ButtonPegawai = new javax.swing.JButton();
        IconDokter = new javax.swing.JLabel();
        IconPerawat = new javax.swing.JLabel();
        IconPegawai = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(700, 800));
        jPanel1.setLayout(null);

        ButtonDokter.setBackground(new java.awt.Color(153, 255, 255));
        ButtonDokter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonDokter.setText("DOKTER");
        ButtonDokter.setBorderPainted(false);
        ButtonDokter.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ButtonDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDokterActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonDokter);
        ButtonDokter.setBounds(210, 379, 190, 30);

        ButtonPerawat.setBackground(new java.awt.Color(153, 255, 255));
        ButtonPerawat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonPerawat.setText("PERAWAT");
        ButtonPerawat.setBorderPainted(false);
        ButtonPerawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPerawatActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPerawat);
        ButtonPerawat.setBounds(450, 380, 190, 30);

        ButtonPegawai.setBackground(new java.awt.Color(153, 255, 255));
        ButtonPegawai.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonPegawai.setText("PEGAWAI");
        ButtonPegawai.setBorderPainted(false);
        ButtonPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPegawaiActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonPegawai);
        ButtonPegawai.setBounds(690, 380, 180, 30);

        IconDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Dokter.png"))); // NOI18N
        jPanel1.add(IconDokter);
        IconDokter.setBounds(220, 230, 180, 180);

        IconPerawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Perawat.png"))); // NOI18N
        jPanel1.add(IconPerawat);
        IconPerawat.setBounds(460, 240, 170, 150);

        IconPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Pegawai.png"))); // NOI18N
        jPanel1.add(IconPegawai);
        IconPegawai.setBounds(700, 240, 160, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CHOOSE YOUR ROLES");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 130, 540, 60);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Blank.png"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(0, -10, 1067, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDokterActionPerformed
        DokterLogin objekDokter = new DokterLogin();
        objekDokter.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonDokterActionPerformed

    private void ButtonPerawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPerawatActionPerformed
        PerawatLogin objekPerawat = new PerawatLogin();
        objekPerawat.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonPerawatActionPerformed

    private void ButtonPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPegawaiActionPerformed
        PegawaiLogin objekPegawai = new PegawaiLogin();
        objekPegawai.setVisible(true);
        dispose();
    }//GEN-LAST:event_ButtonPegawaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetRole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton ButtonDokter;
    private javax.swing.JButton ButtonPegawai;
    private javax.swing.JButton ButtonPerawat;
    private javax.swing.JLabel IconDokter;
    private javax.swing.JLabel IconPegawai;
    private javax.swing.JLabel IconPerawat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
